name: Deploy

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Doorkeeper open
        uses: patoroco/doorkeeper@master
        with:
          digitaloceanToken: ${{ secrets.DO_TOKEN }}
          firewallName: "GitHubActions"
          actionToDo: "add"
          dryRun: false

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: ${{ secrets.IP }}
          password: ${{ secrets.PRIVATE_PASSWORD }}
          script: 'cd /var/www/wase-engine.com && ./deploy.sh'

      - name: Doorkeeper close
        uses: patoroco/doorkeeper@master
        with:
          digitaloceanToken: ${{ secrets.DO_TOKEN }}
          firewallName: "GitHubActions"
          actionToDo: "remove"
          dryRun: false
